# Generated by Django 4.2 on 2023-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='add_date',
        ),
    ]
