# Generated by Django 5.0 on 2024-02-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
